# Generated by Django 2.2.12 on 2021-11-19 11:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория новостей')),
                ('description', models.TextField(verbose_name='Описание категории')),
                ('cat_img', models.ImageField(upload_to='news_list/media/img/news/cat/', verbose_name='Изображение для категории')),
            ],
            options={
                'verbose_name': 'Категория новостей',
                'verbose_name_plural': 'Категории новостей',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_name', models.CharField(max_length=50, verbose_name='Краткий заголовок новости')),
                ('name', models.CharField(max_length=150, verbose_name='Заголовок новости')),
                ('img', models.ImageField(upload_to='news_list/media/img/news/', verbose_name='Изображение новости')),
                ('body', models.TextField(verbose_name='Текст новости')),
                ('post_date', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_list.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Имя пользователя, оставившего комментарий')),
                ('comment_text', models.TextField(max_length=500, verbose_name='Текст коментария')),
                ('comm_post_date', models.DateField(default=datetime.date.today, verbose_name='Дата публикации комментария')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_list.News', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
