# Generated by Django 2.2.12 on 2021-11-23 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название API')),
                ('description', models.TextField(null=True, verbose_name='Подробное описание метода API')),
                ('api_url', models.URLField(verbose_name='Ссылка для запроса API')),
                ('add_date', models.DateField(default=datetime.date.today, verbose_name='Дата добавления метода')),
                ('request_type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
            ],
            options={
                'verbose_name': 'Метод вызова API',
                'verbose_name_plural': 'Методы вызова API',
            },
        ),
    ]
