# Generated by Django 3.2.9 on 2021-11-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilist',
            name='api_url',
            field=models.CharField(max_length=100, verbose_name='Ссылка для запроса API'),
        ),
    ]
